### ISSUE TITLE
set_api_key() security concern

### ISSUE THREAD

**Issue by MikeJohnPage** [CorrelAid/newsanchor#40]
When using `set_api_key()`, there is potential for a users key to be leaked if the `.Rhistory` file associated with their project is published.

While the `.gitignore` file usually takes care of this (at least in RStudio), perhaps it should be made **explicit** in the documentation that `.Rhistory` should be included in the `.gitignore` file when publishing work using `set_api_key()`?

**Comment by MikeJohnPage** [comment]
See pull request #41 for solution.

**Comment by friep** [comment]
fixed as per #41 and the test / import fixes. Thanks for contributing @MikeJohnPage :slightly_smiling_face: :100:
