### ISSUE TITLE
change for sentiment lexicons in tidytext

### ISSUE THREAD

**Issue by juliasilge** [CorrelAid/newsanchor#42]
Hello! My name is Julia Silge and I'm the maintainer of tidytext, one of the packages you use in a vignette for text mining and sentiment analysis. We've done a re-examination of the decision to include so many sentiment lexicons within tidytext in juliasilge/tidytext#131, seeing how the lexicons have various licenses and tidytext has a *different* license. Unfortunately, the AFINN lexicon is one of the lexicons that we've decided to move out of tidytext into a [separate new package](https://github.com/EmilHvitfeldt/textdata) that provides infrastructure for downloading these, with the user agreeing to the terms of the license. Unfortunately, while this change still allows for use in analyses, it makes it more difficult to use these sentiment lexicons in vignettes which will be built on CRAN. 😕

The sentiment lexicon of Bing Liu and collaborators (`get_sentiments("bing")`) is still in tidytext, because those creators have given specific permission for us to include it. One option is for your vignette to switch to that lexicon.

This new version of tidytext is going to be submitted to CRAN in about a week or so, and after that the AFINN lexicon will no longer be available in tidytext. I want to a) let you know so you can update your vignette and b) apologize for how this chain of decisions impacts you!

**Comment by yannikbuhl** [comment]
Thanks for the hint @juliasilge, we'll fix this!

**Comment by friep** [comment]
solved and successfully submitted to CRAN.
