### ISSUE TITLE
query in title parameter

### ISSUE THREAD

**Issue by MDshuey** [CorrelAid/newsanchor#44]
_qInTitle_ is a relatively [new parameter option](https://newsapi.org/docs/endpoints/everything) and is worth including.

**Comment by MDshuey** [comment]
I've forked this and added the parameter in `get_everything.R` and `...all.R ` but haven't checked if the query still has to be null if `qInTitle` isn't.

**Comment by MDshuey** [comment]
I've confirmed that qInTitle can take the place of query (one or the other must be stated)

**Comment by friep** [comment]
closed by #47
